language: smalltalk
sudo: false
os:
- linux
smalltalk:
- Pharo-7.0
env:
  matrix:
  - JOB=test TYPE=System ARCHETYPE=book OUTPUT=pdf
  global:
    secure: sH3fNIlhzf++HrqkJXGvD9sAt41ii/mRwR8gXOgOuH51SJoZAmUx9mKpJvX0DUNU1yUXoCTTCSosBCTQNoXUYKjeXxlwLySHUN68D82hAa6NJpYebdeYI8WgiUYU5tORVwCAIIg//vs4YELFGm02XLJvH11+xmU+5BCeWvWenffd0uj5T+ulKhRQWrDtnlKLnFnxz2wyHEGK6SwtvuQ0kQqqM3WHvkq1b/LIMiFIrDNVMbfkUlosLeLq68AV64B/ev49Zjb8JeTzL7mPj1Gk6GxPyyRquUBf0YDhokeXOESwDUtM4Tr4pnI0QdWTAwSS4ARxf987zGm+MMmFyzNOZEpjzXqtmAZT4vXz9htLuM2MA2lADpp2X3hhjTSSyXz0l6icAYSNGuBJ6GqtNesNsgP59QZnutBa5XbRA69cRoz7bqEbm5Q2S3kgcVgnOzgyCOYBMna3Z/tYOLhtkNs1+zsSp728AuixETDGzqPD5e5PgyKz9NMur2J6AL26AnkofxwoboKw/NAA9+EQskRoMXY5/JFaDpQ43zhrA3qtDhjAqbHKjp9vYgDAV9FQdv2PWybhb6bRamCvPlZOsb9GSiVu+PpcV0MpNKtmMeeM9B0f4JekS+w3gCdwtxeUDQcMIGtrQtx3fMtdmEYwd/yZOSMHZkXNDetK11o2mfeTOBE=
install:
- git clone https://github.com/pillar-markup/pillar.git -b v7.4.1
- cd pillar && ./scripts/build.sh && cd ..
- ". pillar/scripts/ci/ensure_latex.sh"
- "./pillar/scripts/ci/ensure_book_dependencies.sh"
script:
- "./pillar/build/pillar build pdf"
after_success:
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- mv _result/pdf/index.pdf Spec20-wip.pdf
- bash upload.sh Spec20-wip.pdf
branches:
  except:
  - "/^(?i:continuous)$/"
