language: smalltalk
sudo: false
os:
- linux
smalltalk:
- Pharo-7.0
env:
  matrix:
  - JOB=test TYPE=System ARCHETYPE=book OUTPUT=pdf
  global:
  - secure: stB3irK9/gHlRnT0/Ro1XUhDEpXydtd9miGWWZz5U/kJHASKJDKUSIme/t4Guz0CvBhedQWVii9DNIs21XiGPgIu3f7YhIdOJ9mQ/2ygVeUDFZnjiizO64vaoI8OJeLiGn8WoibZHz6Wa57xvZe9kyJZHjpGa3H9S7LKypZyTLREtIckuSwjn6ikP6PnEy5XMPrGZJP6Opc6PK+6McQ1sxKQrLIyrgMV8MrjEmT5xHULCM45rVrxUPGFeaA6mvgegul/LAg/Xxx5/DSy+M8VmJyoVVor4t7JGhvUHcl0jVqDl+FHGJZ8TPt5e5Ai+Av4BJpmGO54sS8GtmqQ+tg4rFSKbKioF/xDowsyrNTsOEplOjnxFW2HEL4o0yFN9HJVZWAcj03A5DCLqsRUltL24VgtAIai4q2MDyaoIkxs0NsS0EvUkrk3t+vo2PHS3nV2C/0tMXMefXEzRzyfWQaeYJNLmdJAqYsuNFGN8fwVI+GOOULVLEh2zP2SVaIVbL3kwREYmmmdpE9d8cWTheRDkgGsdRVN5rBd1AxXEIw71QZ3LDasKOR+rog6wWIqNMcwG3SgySrz2tvUStNodjl4YGKuyVLsniCR2Jstt3GKuQX+qqzCe0T3hE6A7y7dpsdeUS1Fwd4wCISPeWO9rGpDckRdHX9wRsWxwUEFLPENGno=
install:
- git clone https://github.com/pillar-markup/pillar.git -b v7.4.1
- cd pillar && ./scripts/build.sh && cd ..
- ". pillar/scripts/ci/ensure_latex.sh"
- "./pillar/scripts/ci/ensure_book_dependencies.sh"
script:
- "./pillar/build/pillar build pdf"
after_success:
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- mv _result/pdf/index.pdf Spec20-wip.pdf
- bash upload.sh Spec20-wip.pdf
branches:
  except:
  - "/^(?i:continuous)$/"
