language: smalltalk
sudo: false
os:
- linux
smalltalk:
- Pharo-7.0
env:
  matrix:
  - JOB=test TYPE=System ARCHETYPE=book OUTPUT=pdf
install:
- git clone https://github.com/pillar-markup/pillar.git -b v7.4.1
- cd pillar && ./scripts/build.sh && cd ..
- . pillar/scripts/ci/ensure_latex.sh
- ./pillar/scripts/ci/ensure_book_dependencies.sh
script:
- ./pillar/build/pillar build pdf
after_success:
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- mv _result/pdf/index.pdf Spec20-wip.pdf
- bash upload.sh Spec20-wip.pdf
branches:
  except:
  - /^(?i:continuous)$/
