name: SquareBracketAssociates book generation

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prepare Pillar
        run: |
          git clone https://github.com/pillar-markup/pillar.git -b v8.0.12
          ./pillar/scripts/ci/install-texlive
          ./_support/latex/ensure-deps.sh
          ./pillar/scripts/build.sh
          
      - name: Build PDF
        run: pillar build pdf
